version: 2
jobs:
  build:
    docker:      
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: gradle build
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}         
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle 
            - ~/d1    
          key: app-dependencies-{{ checksum "build.gradle" }}
 
            
      - run: gradle test
      

      
     
