
version: 2
jobs:
  build:
    docker:      
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: gradle build
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}         
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle      
          key: app-dependencies-{{ checksum "build.gradle" }}           
      - run: gradle test
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout 
      - run: gradle build
      -  restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}         
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle      
          key: app-dependencies-{{ checksum "build.gradle" }}           
      - run: gradle test
      - run: echo "test job"
  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout 
      - run: gradle build
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}         
            - v1-dependencies-
      - run: gradle dependencies
          
      - run: gradle test
      - run: echo "deploy job"    
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
      - hold:
          type: approval
          requires:
            - build
            - test
      - deploy:
          requires:
            - hold
