version: 2
jobs:
  build:
    docker:      
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: gradle build
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}         
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle 
           
          key: app-dependencies-{{ checksum "build.gradle" }}
 
            
      - run: gradle test
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "data" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts
  test:
    docker:      
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: gradle build
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}         
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle 
           
          key: app-dependencies-{{ checksum "build.gradle" }}        
      - run: echo "$hub"    
workflows:
  version: 2
  commit:
    jobs:
      - test
      - deploy
  nightly:
    triggers:
      - schedule:
          cron: "* * * * *"
